'use client';
import React,{useEffect,useMemo,useState}from'react';
import{Users,UserPlus,ClipboardList,Ruler,Home,Search,Trash2,Edit3,CheckCircle,LogIn,Plus,Phone,Settings,BarChart3,CalendarDays,Wallet,Download,ShieldCheck,Sparkles}from'lucide-react';
import'./style.css';

const empty={workers:[],customers:[],tasks:[],measurements:[],installs:[],payments:[],attendance:[]};
const he={dash:'לוח בקרה',workers:'עובדים',customers:'לקוחות',tasks:'משימות',measurements:'מדידות',installs:'התקנות',payments:'תשלומים',attendance:'כניסת עובדים',reports:'דוחות',settings:'הגדרות',add:'הוספה מהירה',search:'חיפוש מהיר...',name:'שם מלא',phone:'טלפון',address:'כתובת',role:'תפקיד',status:'סטטוס',date:'תאריך',time:'שעה',notes:'הערות',save:'שמירה',delete:'מחיקה',edit:'עריכה',empty:'אין נתונים עדיין',new:'חדש',active:'פעיל',done:'הושלם',pending:'פתוח',inProgress:'בתהליך',customer:'לקוח',worker:'עובד',title:'כותרת',amount:'סכום'};
function uid(){return Math.random().toString(36).slice(2)+Date.now().toString(36)}
const typeTitles={workers:'ניהול עובדים',customers:'ניהול לקוחות',tasks:'ניהול משימות',measurements:'ניהול מדידות',installs:'ניהול התקנות',payments:'ניהול תשלומים',attendance:'כניסת עובדים'};
const nav=[['dash',Home,he.dash],['customers',UserPlus,he.customers],['workers',Users,he.workers],['tasks',ClipboardList,he.tasks],['measurements',Ruler,he.measurements],['installs',CheckCircle,he.installs],['payments',Wallet,he.payments],['attendance',LogIn,he.attendance],['reports',BarChart3,he.reports],['settings',Settings,he.settings]];
export default function App(){const[tab,setTab]=useState('dash');const[q,setQ]=useState('');const[data,setData]=useState(empty);const[form,setForm]=useState({});const[edit,setEdit]=useState(null);useEffect(()=>{try{setData(JSON.parse(localStorage.getItem('kavGoldDataV2'))||empty)}catch{setData(empty)}},[]);useEffect(()=>{localStorage.setItem('kavGoldDataV2',JSON.stringify(data))},[data]);
const stats=useMemo(()=>({workers:data.workers.length,customers:data.customers.length,tasks:data.tasks.length,open:data.tasks.filter(x=>x.status!==he.done).length,measurements:data.measurements.length,installs:data.installs.length,payments:data.payments.reduce((s,x)=>s+(Number(x.amount)||0),0),attendance:data.attendance.length}),[data]);
function addItem(type){const main=form.name||form.title;if(!main){alert('נא למלא שם או כותרת');return}const item={id:edit||uid(),...form,created:new Date().toLocaleString('he-IL')};setData(d=>({...d,[type]:edit?d[type].map(x=>x.id===edit?item:x):[item,...d[type]]}));setForm({});setEdit(null)}
function del(type,id){if(confirm('למחוק את הרשומה?'))setData(d=>({...d,[type]:d[type].filter(x=>x.id!==id)}))}function startEdit(x){setEdit(x.id);setForm(x);window.scrollTo({top:0,behavior:'smooth'})}function match(x){return JSON.stringify(x).toLowerCase().includes(q.toLowerCase())}
function clearAll(){if(confirm('למחוק את כל הנתונים המקומיים?')){setData(empty);localStorage.removeItem('kavGoldDataV2')}}
return <main><aside><div className="brand"><img src="/logo.jpeg"/><div><h1>קו הווילונות הזהב</h1><p>מערכת ניהול פרימיום</p></div></div><div className="profile"><img src="/mohamad.jpeg"/><h2>מוחמד אלחור</h2><span>מנהל מערכת</span><p><Phone size={15}/>052-5956937</p></div><nav>{nav.map(([id,I,txt])=><button key={id} onClick={()=>{setTab(id);setForm({});setEdit(null)}} className={tab===id?'on':''}><I size={19}/>{txt}</button>)}</nav><button className="danger" onClick={clearAll}>איפוס נתונים</button></aside><section><header><div><h1>{tab==='dash'?'לוח בקרה יוקרתי':typeTitles[tab]||nav.find(n=>n[0]===tab)?.[2]}</h1><p>מוחמד אלחור • 052-5956937 • קו הווילונות הזהב</p></div><div className="topActions"><button><ShieldCheck size={18}/> שמירה מקומית</button><button><Sparkles size={18}/> Premium MVP</button></div></header><div className="search"><Search size={18}/><input placeholder={he.search} value={q} onChange={e=>setQ(e.target.value)}/></div>{tab==='dash'?<Dashboard stats={stats} setTab={setTab}/>:tab==='reports'?<Reports stats={stats}/>:tab==='settings'?<SettingsPanel clearAll={clearAll}/>:<Crud type={tab} data={data[tab].filter(match)} form={form} setForm={setForm} addItem={addItem} del={del} startEdit={startEdit} edit={edit}/>}</section></main>}
function Dashboard({stats,setTab}){const cards=[[he.customers,stats.customers,UserPlus,'customers'],[he.workers,stats.workers,Users,'workers'],[he.tasks,stats.tasks,ClipboardList,'tasks'],['משימות פתוחות',stats.open,BarChart3,'tasks'],[he.measurements,stats.measurements,Ruler,'measurements'],[he.installs,stats.installs,CheckCircle,'installs'],['סה״כ תשלומים','₪ '+stats.payments.toLocaleString('he-IL'),Wallet,'payments'],[he.attendance,stats.attendance,LogIn,'attendance']];return <><div className="hero"><div><span className="badge">Premium Luxury Dashboard</span><h2>ניהול וילונות ברמה אחרת</h2><p>לקוחות, עובדים, משימות, מדידות, התקנות ותשלומים — הכול במקום אחד, בעיצוב שחור־זהב יוקרתי.</p><div className="heroBtns"><button onClick={()=>setTab('customers')}>לקוח חדש</button><button onClick={()=>setTab('tasks')}>משימה חדשה</button></div></div><img src="/mohamad.jpeg"/></div><div className="grid">{cards.map(([a,b,I,tab])=><button className="card" onClick={()=>setTab(tab)} key={a}><I/><span>{a}</span><strong>{b}</strong></button>)}</div><div className="dashRows"><div className="panel"><h3>פעולות מהירות</h3><button onClick={()=>setTab('customers')}>+ הוספת לקוח חדש</button><button onClick={()=>setTab('workers')}>+ הוספת עובד חדש</button><button onClick={()=>setTab('measurements')}>+ פתיחת מדידה</button><button onClick={()=>setTab('installs')}>+ פתיחת התקנה</button></div><div className="panel"><h3>סטטוס מערכת</h3><p>המערכת מוכנה לעבודה. כל הטבלאות מתחילות ריקות, וכל נתון שתוסיף יישמר בדפדפן.</p><p className="gold">השלב הבא: חיבור למסד נתונים אמיתי כדי שכל המכשירים יראו את אותם נתונים.</p></div></div></>}
function Crud({type,data,form,setForm,addItem,del,startEdit,edit}){const isTask=['tasks','measurements','installs'].includes(type);const isPay=type==='payments';const isAttendance=type==='attendance';return <div className="work"><div className="panel form"><h2>{edit?'עריכת רשומה':'הוספת רשומה חדשה'}</h2><div className="fields"><input placeholder={isTask?he.title:he.name} value={form.name||form.title||''} onChange={e=>setForm({...form,[isTask?'title':'name']:e.target.value})}/>{!isPay&&<input placeholder={he.phone} value={form.phone||''} onChange={e=>setForm({...form,phone:e.target.value})}/>}<input placeholder={he.customer} value={form.customer||''} onChange={e=>setForm({...form,customer:e.target.value})}/><input placeholder={he.worker} value={form.worker||''} onChange={e=>setForm({...form,worker:e.target.value})}/><input placeholder={he.address} value={form.address||''} onChange={e=>setForm({...form,address:e.target.value})}/>{isPay&&<input type="number" placeholder={he.amount} value={form.amount||''} onChange={e=>setForm({...form,amount:e.target.value})}/>}<input type="date" value={form.date||''} onChange={e=>setForm({...form,date:e.target.value})}/>{isAttendance&&<input type="time" value={form.time||''} onChange={e=>setForm({...form,time:e.target.value})}/>}<select value={form.status||he.pending} onChange={e=>setForm({...form,status:e.target.value})}><option>{he.pending}</option><option>{he.active}</option><option>{he.inProgress}</option><option>{he.done}</option></select><textarea placeholder={he.notes} value={form.notes||''} onChange={e=>setForm({...form,notes:e.target.value})}/></div><button className="save" onClick={()=>addItem(type)}><Plus size={18}/>{he.save}</button></div><div className="list">{data.length===0?<div className="empty">{he.empty}</div>:data.map(x=><article key={x.id}><div><h3>{x.name||x.title}</h3><p>{[x.phone,x.customer&&'לקוח: '+x.customer,x.worker&&'עובד: '+x.worker,x.address].filter(Boolean).join(' • ')}</p><small>{[x.status,x.date,x.time,x.amount&&'₪ '+x.amount].filter(Boolean).join(' • ')}</small>{x.notes&&<p>{x.notes}</p>}</div><div className="actions"><button onClick={()=>startEdit(x)}><Edit3 size={16}/></button><button onClick={()=>del(type,x.id)}><Trash2 size={16}/></button></div></article>)}</div></div>}
function Reports({stats}){return <div className="panel reports"><h2>דוחות וסיכום</h2><div className="grid small"><div>לקוחות <b>{stats.customers}</b></div><div>עובדים <b>{stats.workers}</b></div><div>משימות <b>{stats.tasks}</b></div><div>תשלומים <b>₪ {stats.payments.toLocaleString('he-IL')}</b></div></div><button onClick={()=>window.print()}><Download size={18}/> הדפסה / שמירה כ-PDF</button></div>}
function SettingsPanel({clearAll}){return <div className="panel"><h2>הגדרות</h2><p>שם מנהל: מוחמד אלחור</p><p>טלפון: 052-5956937</p><p>עסק: קו הווילונות הזהב</p><button className="danger" onClick={clearAll}>מחיקת כל הנתונים המקומיים</button></div>}
